const form=document.querySelector("#myForm");const lastNameInput=document.querySelector("#lastName");const firstNameInput=document.querySelector("#firstName");const emailInput=document.querySelector("#email");const objetInput=document.querySelector("#objet");const messageInput=document.querySelector("#message");const agreedSelect=document.querySelector("#agreed");const submitBtn=document.querySelector("#submitBtn");let lastNameInputOK=false;let firstNameInputOK=false;let emailInputOK=false;let objetInputOK=false;let messageInputOK=false;function updateButtonStyle(){if(!submitBtn.disabled){submitBtn.style.backgroundColor="green";submitBtn.style.color="white";submitBtn.style.cursor="pointer";}else{submitBtn.style.backgroundColor="gray";submitBtn.style.color="white";submitBtn.style.cursor="not-allowed";}}
function disableButton(){submitBtn.disabled=!(firstNameInputOK&&lastNameInputOK&&emailInputOK&&objetInputOK&&messageInputOK&&agreedSelect.checked);updateButtonStyle();}
function createErrorMessage(errorId,errorMessage,input){let errorElement=document.querySelector(`#${errorId}`);if(!errorElement){errorElement=document.createElement("p");errorElement.textContent=`⚠️ ${errorMessage}`;errorElement.id=errorId;errorElement.style.color="#d32f2f";errorElement.style.backgroundColor="#ffebee";errorElement.style.border="1px solid #d32f2f";errorElement.style.padding="8px";errorElement.style.borderRadius="5px";errorElement.style.fontSize="14px";errorElement.style.marginTop="5px";errorElement.style.maxWidth="400px";input.after(errorElement);}}
function validateLength(input,errorId,min,max,fieldName){let isValid=true;let errorElement=document.querySelector(`#${errorId}`);let value=input.value.trim();if(value.length<min||value.length>max){createErrorMessage(errorId,`${fieldName}doit contenir entre ${min}et ${max}caractères.`,input);isValid=false;}else{if(errorElement)errorElement.remove();isValid=true;}
return isValid;}
function validateEmail(input,errorId){let isValid=true;const emailRegex=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;let errorElement=document.querySelector(`#${errorId}`);if(!emailRegex.test(input.value.trim())){createErrorMessage(errorId,"Veuillez saisir une adresse email valide.",input);isValid=false;}else{if(errorElement)errorElement.remove();isValid=true;}
return isValid;}
firstNameInput.addEventListener("input",function(){firstNameInputOK=validateLength(firstNameInput,"erreurFirstName",2,50,"Le prénom");disableButton();});lastNameInput.addEventListener("input",function(){lastNameInputOK=validateLength(lastNameInput,"erreurLastName",2,50,"Le nom");disableButton();});emailInput.addEventListener("input",function(){emailInputOK=validateEmail(emailInput,"erreurEmail");disableButton();});objetInput.addEventListener("input",function(){objetInputOK=validateLength(objetInput,"erreurObjet",3,250,"L'objet");disableButton();});messageInput.addEventListener("input",function(){messageInputOK=validateLength(messageInput,"erreurMessage",3,250,"Le message");disableButton();});form.addEventListener("submit",function(event){event.preventDefault();firstNameInputOK=validateLength(firstNameInput,"erreurFirstName",2,50,"Le prénom");lastNameInputOK=validateLength(lastNameInput,"erreurLastName",2,50,"Le nom");emailInputOK=validateEmail(emailInput,"erreurEmail");objetInputOK=validateLength(objetInput,"erreurObjet",3,250,"L'objet");messageInputOK=validateLength(messageInput,"erreurMessage",3,250,"Le message");let erreurAgreed=document.querySelector("#erreurAgreed");if(!agreedSelect.checked){if(!erreurAgreed){createErrorMessage("erreurAgreed","Vous devez accepter les conditions d'utilisation.",agreedSelect.parentElement);}}else{if(erreurAgreed)erreurAgreed.remove();}
disableButton();if(firstNameInputOK&&lastNameInputOK&&emailInputOK&&objetInputOK&&messageInputOK&&agreedSelect.checked){alert("Formulaire soumis avec succès !");form.submit();}});agreedSelect.addEventListener("change",function(){const erreurAgreed=document.querySelector("#erreurAgreed");if(agreedSelect.checked&&erreurAgreed){erreurAgreed.remove();}
disableButton();});updateButtonStyle();